
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */

#pragma once

#include <tvm/schema/message.hpp>
#include <tvm/smart_switcher.hpp>
#include <tvm/contract_handle.hpp>


namespace tvm { namespace schema {

struct Wittness {
    bytes primary_input;
    bytes auxiliary_input;
};


__interface ICircuitUtil {

  [[external, dyn_chain_parse]]
  void constructor(uint256 pubkey) = 1;

  [[getter]]
  Wittness generateWitness(uint32 a, uint32 b) = 2;
};

struct DCircuitUtil {
};

__interface ECircuitUtil {
};

}} // namespace tvm::schema
